### ISSUE TITLE
Cannot get process details

### ISSUE THREAD

**Issue by vtereshkov** [CUSTIS-public/ProcInsp#1]
I have managed to get the process list and RAM/CPU usage estimates. However, after clicking the process name, I get the following error message:
```
Error while data fetch http://localhost:5000/Process/6504/threadSizes: SyntaxError: Unexpected token < in JSON at position 0
```
No process info is displayed.

**Comment by ishatalkin** [comment]
The reason could be one of the following: 
1) The process is not CLR one;
2) The user, under which server-side is running, hasn't got necessary privileges.

Please, be sure that you are clicking on a CLR-process. Simple CLR-application could be found [here](https://drive.google.com/file/d/12HQa2Ih7tfHyrKAUKKOdEG6LkaNZDmZb/view?usp=sharing). Just unzip archive and run w3wp.exe. Please, let me know, if information is shown about CLR-process.

You can get a list of CLR processe, running on your machine, with the following CMD: `tasklist /m "mscor*"`

**Comment by vtereshkov** [comment]
@ishatalkin Yes, I get the full process data (including stack traces) for `w3wp.exe` and `ProcInsp.exe`. On the other hand, the `MOM.exe` and `CCC.exe` processes are also listed by `tasklist /m "mscor*"` but fail to show anything meaningful except the same error message. The `WmiPrvSE.exe` shows neither the error message nor the process info. 

Is that right that I cannot get any info for a native x86 process (compiled from C/C++ etc.)?

**Comment by ishatalkin** [comment]
The other problem may be the difference between target architecture of ProcInsp and process under inspection. This is the [limitation](https://github.com/CUSTIS-public/ProcInsp#known-limitations) of ProcInsp. 

I'll add user-friendly error message, which will describe, why information is not gathered.

`Is that right that I cannot get any info for a native x86 process (compiled from C/C++ etc.)?`
For such a process you can get only overall info (such as CPU and RAM usage), but you can't drill down to thread list.

**Comment by vtereshkov** [comment]
@ishatalkin Ok, thank you.

**Comment by ishatalkin** [comment]
@vtereshkov , I added user friendly error messages. Please, try version [1.1.0](https://github.com/CUSTIS-public/ProcInsp/releases/tag/v1.1.0). 

For non CLR processes ProcInsp retrieves thread IDs with their status and start time. Such information as callstack or thread exception is not collected.
