### ISSUE TITLE
Show appropriate message when exception occured while retrieving information

### ISSUE THREAD

**Issue by ishatalkin** [CUSTIS-public/ProcInsp#2]
If user clicks on not a CLR-process, he gets the following error:
```Error while data fetch http://localhost:5000/Process/6504/threadSizes: SyntaxError: Unexpected token < in JSON at position 0```

Expected behaviour: to show appropriate message

**Comment by ishatalkin** [comment]
Fixed it in 1.1.0

**Comment by vtereshkov** [comment]
Confirmed. Thank you.
